

SELECT*FROM Usuarios
SELECT*FROM DIRECCIONUSUARIOS
SELECT*FROM Artistas
SELECT*FROM Eventos


SELECT * FROM USUARIOS
WHERE EDAD > 21

SELECT DIRECCION_ID,CIUDAD,PAIS FROM DIRECCIONUSUARIOS
WHERE CIUDAD LIKE '[A-M]%'

SELECT ARTISTAS.NOMBREARTISTA,ARTISTAS.GENERO,EVENTOS.NOMBRE,
EVENTOS.FECHAINICIO,EVENTOS.FECHAVENTA 
FROM ARTISTAS INNER JOIN EVENTOS 
ON ARTISTAS.ARTISTA_ID=EVENTOS.ARTISTA_ID 

SELECT USUARIOS.PRIMERNOMBRE,USUARIOS.PRIMERNOMBRE,USUARIOS.APELLIDO,
USUARIOS.GENERO,DIRECCIONUSUARIOS.PAIS,DIRECCIONUSUARIOS.CIUDAD,DIRECCIONUSUARIOS.TELEFONO
FROM USUARIOS INNER JOIN DIRECCIONUSUARIOS 
ON USUARIOS.DIRECCION_ID=DIRECCIONUSUARIOS.DIRECCION_ID

SELECT *
FROM USUARIOS U 
LEFT JOIN DireccionUsuarios D
ON U.correo = D.pais

SELECT *
FROM Eventos E 
LEFT JOIN SedeEvento S
ON E.evento_id = S.direccion_id

SELECT GENERO FROM Artistas GROUP BY GENERO

Select sede_id,SUM (numeroFila)
from dbo.SedeFilas
Group by sede_id
having sum(numeroFila) > 3

SELECT SEDE_ID , SUM (CAPACIDADASIENTOS)
FROM DBO.SEDEEVENTO
GROUP BY SEDE_ID
HAVING SUM (CAPACIDADASIENTOS) > 3000

SELECT NOMBRESEDE, SUM (CAPACIDADASIENTOS)
FROM DBO.SEDEEVENTO
GROUP BY NOMBRESEDE
HAVING NOMBRESEDE ='Nombre desconocido'

SELECT APELLIDO
FROM DBO.Usuarios
GROUP BY APELLIDO
HAVING (APELLIDO) = 'ESCUTIA'

SELECT * INTO SEDEFILASBACKUP FROM SEDEEVENTO

DROP TABLE SEDEFILASBACKUP